/** Canonical tenant RBAC keys — keep in sync with backend permission-catalog.ts */
export const ALL_PERMISSIONS = [
  "view_products",
  "create_product",
  "edit_product",
  "delete_product",
  "adjust_inventory",
  "transfer_inventory",
  "approve_transfer",
  "view_expenses",
  "create_expense",
  "edit_expense",
  "delete_expense",
  "view_suppliers",
  "create_supplier",
  "edit_supplier",
  "delete_supplier",
  "view_purchases",
  "create_purchase",
  "edit_purchase",
  "delete_purchase",
  "receive_purchase",
  "post_purchase_invoice",
  "view_sales",
  "create_sale",
  "refund_sale",
  "void_sale",
  "view_transaction_register",
  "manage_pricing",
  "manage_price_groups",
  "manage_offers",
  "view_customer_credit",
  "create_customer_credit_sale",
  "record_customer_repayment",
  "override_credit_limit",
  "pos_approve_variance",
  "view_customers",
  "create_customer",
  "edit_customer",
  "delete_customer",
  "manage_users",
  "view_staff",
  "create_staff",
  "edit_staff",
  "delete_staff",
  "view_roles",
  "create_role",
  "edit_role",
  "delete_role",
  "assign_role",
  "view_pos_terminals",
  "manage_pos_terminals",
  "edit_branch",
  "change_lock_date",
  "import_products",
  "import_opening_stock",
  "view_import_center",
  "cleanup_import_products",
  "manage_accounting_configuration",
  "post_journal",
  "reverse_journal",
  "close_period",
  "reopen_period",
  "view_reports",
  "view_audit_logs",
  "export_audit_package",
  "view_disclosure_reports",
  "run_consolidation",
  "reverse_consolidation",
  "view_consolidation_history",
  "finalize_consolidation",
  "approve_consolidation_adjustments",
] as const;

export type PermissionName = (typeof ALL_PERMISSIONS)[number];

export type PermissionGroupId =
  | "inventory"
  | "purchasing"
  | "sales"
  | "accounting"
  | "administration"
  | "imports"
  | "customer_credit"
  | "pricing"
  | "audit"
  | "consolidation";

export const PERMISSION_GROUP_LABELS: Record<PermissionGroupId, string> = {
  inventory: "Inventory",
  purchasing: "Purchasing",
  sales: "Sales",
  accounting: "Accounting",
  administration: "Administration",
  imports: "Imports",
  customer_credit: "Customer Credit",
  pricing: "Pricing & Offers",
  audit: "Audit",
  consolidation: "Consolidation",
};

export const PERMISSION_GROUPS: Record<PermissionGroupId, PermissionName[]> = {
  inventory: [
    "view_products",
    "create_product",
    "edit_product",
    "delete_product",
    "adjust_inventory",
    "transfer_inventory",
    "approve_transfer",
  ],
  purchasing: [
    "view_suppliers",
    "create_supplier",
    "edit_supplier",
    "delete_supplier",
    "view_purchases",
    "create_purchase",
    "edit_purchase",
    "delete_purchase",
    "receive_purchase",
    "post_purchase_invoice",
  ],
  sales: [
    "view_sales",
    "create_sale",
    "refund_sale",
    "void_sale",
    "view_transaction_register",
  ],
  pricing: ["manage_pricing", "manage_price_groups", "manage_offers"],
  customer_credit: [
    "view_customers",
    "create_customer",
    "edit_customer",
    "delete_customer",
    "view_customer_credit",
    "create_customer_credit_sale",
    "record_customer_repayment",
    "override_credit_limit",
  ],
  administration: [
    "manage_users",
    "view_staff",
    "create_staff",
    "edit_staff",
    "delete_staff",
    "view_roles",
    "create_role",
    "edit_role",
    "delete_role",
    "assign_role",
    "view_pos_terminals",
    "manage_pos_terminals",
    "pos_approve_variance",
    "edit_branch",
    "change_lock_date",
  ],
  imports: [
    "import_products",
    "import_opening_stock",
    "view_import_center",
    "cleanup_import_products",
  ],
  accounting: [
    "view_expenses",
    "create_expense",
    "edit_expense",
    "delete_expense",
    "manage_accounting_configuration",
    "post_journal",
    "reverse_journal",
    "close_period",
    "reopen_period",
    "view_reports",
  ],
  audit: ["view_audit_logs", "export_audit_package", "view_disclosure_reports"],
  consolidation: [
    "run_consolidation",
    "reverse_consolidation",
    "view_consolidation_history",
    "finalize_consolidation",
    "approve_consolidation_adjustments",
  ],
};

export const COARSE_PERMISSION_ALIASES: ReadonlyArray<{
  coarse: PermissionName;
  implies: readonly PermissionName[];
}> = [
  {
    coarse: "manage_users",
    implies: [
      "view_staff",
      "create_staff",
      "edit_staff",
      "delete_staff",
      "view_roles",
      "create_role",
      "edit_role",
      "delete_role",
      "assign_role",
      "view_pos_terminals",
      "manage_pos_terminals",
    ],
  },
  {
    coarse: "manage_pricing",
    implies: ["view_products", "edit_product", "manage_pricing"],
  },
  {
    coarse: "manage_price_groups",
    implies: ["manage_price_groups"],
  },
  {
    coarse: "manage_offers",
    implies: ["manage_offers"],
  },
  {
    coarse: "manage_accounting_configuration",
    implies: ["manage_accounting_configuration", "view_reports"],
  },
];

export function expandPermissionCodes(codes: readonly string[]): Set<string> {
  const out = new Set<string>();
  for (const code of codes) {
    const trimmed = code.trim();
    if (!trimmed) continue;
    out.add(trimmed);
    for (const alias of COARSE_PERMISSION_ALIASES) {
      if (trimmed === alias.coarse) {
        for (const implied of alias.implies) out.add(implied);
      }
    }
  }
  return out;
}

export function getEffectivePermissions(codes: readonly string[]): Set<string> {
  return expandPermissionCodes(codes);
}

export function hasEffectivePermission(
  codes: readonly string[],
  required: string,
): boolean {
  return expandPermissionCodes(codes).has(required.trim());
}

/** Short column titles for dense tables */
export const PERMISSION_SHORT_LABEL: Record<PermissionName, string> = {
  view_products: "View prod",
  create_product: "Create",
  edit_product: "Edit",
  delete_product: "Del",
  adjust_inventory: "Adjust",
  transfer_inventory: "Transfer",
  approve_transfer: "Appr xfr",
  view_expenses: "View exp",
  create_expense: "Create exp",
  edit_expense: "Edit exp",
  delete_expense: "Del exp",
  view_suppliers: "View sup",
  create_supplier: "Create sup",
  edit_supplier: "Edit sup",
  delete_supplier: "Del sup",
  view_purchases: "View purch",
  create_purchase: "Create purch",
  edit_purchase: "Edit purch",
  delete_purchase: "Del purch",
  receive_purchase: "Receive",
  post_purchase_invoice: "Post inv",
  view_sales: "View sales",
  create_sale: "Create sale",
  refund_sale: "Refund",
  void_sale: "Void",
  view_transaction_register: "Txn reg",
  manage_pricing: "Pricing",
  manage_price_groups: "Price grp",
  manage_offers: "Offers",
  view_customer_credit: "Credit view",
  create_customer_credit_sale: "Credit sale",
  record_customer_repayment: "Repayment",
  override_credit_limit: "Credit ovr",
  pos_approve_variance: "POS appr",
  view_customers: "View cust",
  create_customer: "Create cust",
  edit_customer: "Edit cust",
  delete_customer: "Del cust",
  manage_users: "Users",
  view_staff: "View staff",
  create_staff: "Create staff",
  edit_staff: "Edit staff",
  delete_staff: "Del staff",
  view_roles: "View roles",
  create_role: "Create role",
  edit_role: "Edit role",
  delete_role: "Del role",
  assign_role: "Assign role",
  view_pos_terminals: "POS terms",
  manage_pos_terminals: "POS mgmt",
  edit_branch: "Edit branch",
  change_lock_date: "Lock date",
  import_products: "Import",
  import_opening_stock: "Open stk",
  view_import_center: "Import ctr",
  cleanup_import_products: "Import cln",
  manage_accounting_configuration: "Acct config",
  post_journal: "Post jrnl",
  reverse_journal: "Rev jrnl",
  close_period: "Close per",
  reopen_period: "Reopen per",
  view_reports: "Reports",
  view_audit_logs: "Audit log",
  export_audit_package: "Audit exp",
  view_disclosure_reports: "Disclosure",
  run_consolidation: "Cons run",
  reverse_consolidation: "Cons rev",
  view_consolidation_history: "Cons hist",
  finalize_consolidation: "Cons fin",
  approve_consolidation_adjustments: "Cons adj",
};

/** Full labels for CSV export and tooltips */
export const PERMISSION_FULL_LABEL: Record<PermissionName, string> = {
  view_products: "View products",
  create_product: "Create products",
  edit_product: "Edit products",
  delete_product: "Delete products",
  adjust_inventory: "Adjust inventory",
  transfer_inventory: "Transfer inventory",
  approve_transfer: "Approve transfers",
  view_expenses: "View expenses",
  create_expense: "Create expenses",
  edit_expense: "Edit expenses",
  delete_expense: "Delete expenses",
  view_suppliers: "View suppliers",
  create_supplier: "Create suppliers",
  edit_supplier: "Edit suppliers",
  delete_supplier: "Delete suppliers",
  view_purchases: "View purchases",
  create_purchase: "Create purchases",
  edit_purchase: "Edit purchases",
  delete_purchase: "Delete purchases",
  receive_purchase: "Receive purchases",
  post_purchase_invoice: "Post purchase invoice",
  view_sales: "View sales",
  create_sale: "Create sales",
  refund_sale: "Refund sales",
  void_sale: "Void sales",
  view_transaction_register: "View transaction register",
  manage_pricing: "Manage pricing",
  manage_price_groups: "Manage price groups",
  manage_offers: "Manage offers",
  view_customer_credit: "View customer credit",
  create_customer_credit_sale: "Create customer credit sale",
  record_customer_repayment: "Record customer repayment",
  override_credit_limit: "Override credit limit",
  pos_approve_variance: "Approve POS variance",
  view_customers: "View customers",
  create_customer: "Create customers",
  edit_customer: "Edit customers",
  delete_customer: "Delete customers",
  manage_users: "Manage users (legacy)",
  view_staff: "View staff",
  create_staff: "Create staff",
  edit_staff: "Edit staff",
  delete_staff: "Delete staff",
  view_roles: "View roles",
  create_role: "Create roles",
  edit_role: "Edit roles",
  delete_role: "Delete roles",
  assign_role: "Assign roles",
  view_pos_terminals: "View POS terminals",
  manage_pos_terminals: "Manage POS terminals",
  edit_branch: "Edit branches",
  change_lock_date: "Change accounting lock date",
  import_products: "Import products",
  import_opening_stock: "Import opening stock",
  view_import_center: "View Import Center",
  cleanup_import_products: "Cleanup import products",
  manage_accounting_configuration: "Manage accounting configuration",
  post_journal: "Post journal entry",
  reverse_journal: "Reverse journal entry",
  close_period: "Close accounting period",
  reopen_period: "Reopen accounting period",
  view_reports: "View reports",
  view_audit_logs: "View audit logs",
  export_audit_package: "Export audit package",
  view_disclosure_reports: "View disclosure reports",
  run_consolidation: "Run consolidation",
  reverse_consolidation: "Reverse consolidation",
  view_consolidation_history: "View consolidation history",
  finalize_consolidation: "Finalize consolidation",
  approve_consolidation_adjustments: "Approve consolidation adjustments",
};

/** Role editor descriptions for permissions UI */
export const PERMISSION_DESCRIPTIONS: Partial<Record<PermissionName, string>> = {
  view_products: "View product catalog and details.",
  create_product: "Create new products in the catalog.",
  edit_product: "Edit product details, categories, and UOM definitions.",
  delete_product: "Permanently delete products from the catalog.",
  adjust_inventory: "Manual inventory adjustments.",
  transfer_inventory: "Create and operate stock transfers.",
  approve_transfer: "Approve or reject stock transfer requests.",
  view_expenses: "View operating expense records.",
  create_expense: "Record operating expenses.",
  edit_expense: "Edit expense records.",
  delete_expense: "Delete expense records.",
  view_suppliers: "View supplier records.",
  create_supplier: "Create supplier records.",
  edit_supplier: "Edit supplier records.",
  delete_supplier: "Delete supplier records.",
  view_purchases: "View purchase bills and orders.",
  create_purchase: "Create purchase documents.",
  edit_purchase: "Edit draft purchase documents.",
  delete_purchase: "Delete purchase documents.",
  receive_purchase: "Receive stock against purchase orders.",
  post_purchase_invoice: "Post purchase invoices to accounting.",
  view_sales: "View sales documents.",
  create_sale: "Create sales and POS transactions.",
  refund_sale: "Process sale refunds and returns.",
  void_sale: "Void sales transactions.",
  view_transaction_register: "View the POS transaction register.",
  manage_pricing: "Manage product pricing and bulk price updates.",
  manage_price_groups: "Create and edit price groups.",
  manage_offers: "Create, edit, enable, and disable promotional offers.",
  manage_users: "Legacy alias for all staff and role permissions.",
  view_staff: "View staff list and details.",
  create_staff: "Create staff accounts.",
  edit_staff: "Edit staff accounts.",
  delete_staff: "Delete staff accounts.",
  view_roles: "View roles and permission assignments.",
  create_role: "Create custom roles.",
  edit_role: "Edit role permissions and metadata.",
  delete_role: "Delete unused custom roles.",
  assign_role: "Assign roles to staff.",
  view_pos_terminals: "View POS terminal registry and status.",
  manage_pos_terminals: "Create, edit, reset, and revoke POS terminals.",
  pos_approve_variance:
    "Approve shift cash variance and supervisor POS actions.",
  edit_branch: "Edit branch settings (excluding lock date).",
  change_lock_date: "Manually change branch accounting lock dates.",
  import_products: "Import products via spreadsheet or Import Center.",
  import_opening_stock: "Import opening stock balances.",
  view_import_center: "Access the Import Center administration page.",
  cleanup_import_products: "Remove failed or partial product import jobs.",
  manage_accounting_configuration:
    "Configure chart of accounts, journals, and accounting settings.",
  post_journal: "Post manual journal entries.",
  reverse_journal: "Reverse journal entries (when supported).",
  close_period: "Close an accounting period and advance lock date.",
  reopen_period: "Reopen a closed accounting period.",
  view_reports: "View standard business and financial reports.",
  view_audit_logs: "View audit trail and journal audit pages.",
  export_audit_package: "Export audit chain CSV and audit packages.",
  view_disclosure_reports: "View consolidation disclosure reports.",
  view_customer_credit: "View customer credit balances and history.",
  create_customer_credit_sale: "Create sales on customer credit.",
  record_customer_repayment: "Record customer credit repayments.",
  override_credit_limit: "Override customer credit limits and POS discount caps.",
  view_customers: "View customer records.",
  create_customer: "Create customer records.",
  edit_customer: "Edit customer records.",
  delete_customer: "Delete customer records.",
  run_consolidation: "Run branch consolidation for financial reporting.",
  reverse_consolidation: "Reverse a posted consolidation run.",
  view_consolidation_history: "View consolidation run history.",
  finalize_consolidation: "Finalize consolidation runs.",
  approve_consolidation_adjustments: "Approve consolidation adjustment entries.",
};
