[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --filter ./apps/qoondeeye-pharmacyDB..."
]

[phases.build]
cmds = [
  "pnpm --filter ./apps/qoondeeye-pharmacyDB prisma generate",
  "pnpm --filter ./apps/qoondeeye-pharmacyDB prisma migrate deploy",
  "pnpm --filter ./apps/qoondeeye-pharmacyDB run build"
]

[start]
cmd = "pnpm --filter ./apps/qoondeeye-pharmacyDB run start:prod"