[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = [
  "rm -f pnpm-workspace.yaml",
  "pnpm install"
]

[phases.build]
cmds = [
  "pnpm prisma generate",
  "pnpm prisma migrate deploy",
  "pnpm run build"
]

[start]
cmd = "pnpm run start:prod"