// This file was generated by Prisma, and assumes you have installed the following:
// pnpm add -D prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // DATABASE_URL: Render/production. Staging/local for shared dev DBs.
    url:
      process.env['DATABASE_URL'] ??
      process.env['DATABASE_URL_STAGING'] ??
      process.env['DATABASE_URL_LOCAL'],
  },
});
