// This file was generated by Prisma, and assumes you have installed the following:
// pnpm add -D prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url:
      process.env.NODE_ENV === 'production'
        ? process.env['DATABASE_URL_STAGING']
        : (process.env['DATABASE_URL_LOCAL'] ??
          process.env['DATABASE_URL_STAGING']),
  },
});
